wedul:
  client:
    url: localhost
    port: 8081
    timeout: 1
    socket-timeout: 4000
    connect-timeout: 1

wedul-test:
  client:
    url: 192.168.219.151
    port: 8081
    timeout: 3000
    socket-timeout: 3000
    connect-timeout: 3000

resilience4j:
  circuitbreaker:
    backends:
      wedul:
        ringBufferSizeInClosedState: 13
        ringBufferSizeInHalfOpenState: 30
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 20
        registerHealthIndicator: false


server:
  port: 8081
---
spring:
  profiles: develop

server:
  port: 8080

